#########################################
# --- Default Options for All Pages --- #
#########################################

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      struct:
          - type: layout-one-column
            page: [post-title, banner-rounded, post-content]
      permalink: blog/:slug
  - scope:
      path: ""
      type: "category"
    values:
      card: card-3
      struct:
          - type: layout-one-column
            page: [card-list]

#######################
# --- Collections --- #
#######################

collections:
  category:
    output: true
    permalink: category/:name

###################
# --- Plugins --- #
###################

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

########################
# --- Custom Theme --- #
########################

remote_theme: Dean-J-K-James/dodo-web-engine-jekyll-theme
